#! /bin/bash


qemu-system-x86_64 \
    -smp 2 \
    -m 1024 \
    -nographic \
    -drive format=qcow2,file=ubuntu-16.04-server-cloudimg-amd64-disk1.img \
    -drive format=raw,file=cloud.img \
    -device e1000,netdev=net0 \
    -netdev user,id=net0,\
hostfwd=tcp::2222-:22,\
hostfwd=tcp::8080-:80,\
hostfwd=tcp::4443-:443
